### ISSUE TITLE
Peer-to-peer code review

### ISSUE THREAD

**Issue by Behnam1369** [VicPeralta/ChessEvent#3]
Good job Victor. Your work looks amazing. We really enjoyed reviewing your code. 👏 

- You have split your codes into multiple smaller sections which are nice and help to track everything easier. ✔️ 
- You have used good comments for explaining the functionality of your code. ✔️ 

And there are a few optional suggestions that may improve your code :

- You can make your cards grow and shrink when  resizing the page 
- You may want to remove the extra empty white bar above the footer.
- You can make your header section fullscreen.  
- You can use a filter effect or an overlay element on your images to make them more consistent with template design. 

Good luck and happy coding.

**Comment by VicPeralta** [comment]
Thank you for your comments.
Based on your feedback I made these changes:

- Remove the extra empty space above the footer. In fact in the desktop version, I moved the partner section to below the speaker section, I haven't noticed that. But now it looks like the original design.
- I changed the welcome section to be min-height: 100vh
- Added a filter effect to the past event images so the text is easier to read
- Remove the fixed partner image and used instead a partners container filled with partner cards that contain an image and a text that better describe the partner.
- Made the partner section responsive, so the cards arranged accordingly with the space available
Thanks for your feedback, now the project looks a lot better.
